site_name: Docker for Data Scientists
site_url: https://www.data-mining.co.nz/docker-for-data-scientists/
site_description: From one data scientist to another on how to utilize docker to make your life easier
repo_url: https://github.com/waikato-datamining/docker-for-data-scientists
edit_uri: edit/main/docs/
theme:
    name: readthedocs
markdown_extensions:
    - toc:
        baselevel: 2
        permalink: "#"
plugins:
    - search
nav:
  - 'Home': index.md
  - 'Basics': basics.md
  - 'Repositories': repos.md
  - 'Dockerfile': dockerfile.md
  - 'Best practices': best_practices.md
  - 'Tips & Tricks': tips_and_tricks.md
  - 'Troubleshooting': troubleshooting.md
  - 'Automation': automation.md
  - 'Registry': registry.md
